import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, engine, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.engine = engine
        self.setupUi(engine.MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 530)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.Oscreen = Oscilloscope(self.centralwidget)
        self.Oscreen.setGeometry(QtCore.QRect(10, 10, 771, 481))
        self.Oscreen.setMinimumSize(QtCore.QSize(771, 481))
        self.Oscreen.setMaximumSize(QtCore.QSize(771, 481))
        self.Oscreen.setObjectName("graphWidget")

        self.pushButtonStartStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStartStop.setGeometry(QtCore.QRect(810, 10, 100, 30))
        self.pushButtonStartStop.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonStartStop.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonStartStop.setFont(font)
        self.pushButtonStartStop.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonStartStop.setCheckable(False)
        self.pushButtonStartStop.setObjectName("pushButtonStartStop")

        self.pushButtonClear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(910, 10, 100, 30))
        self.pushButtonClear.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButtonClear.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonClear.setObjectName("pushButtonClear")

        self.groupBoxVertical = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxVertical.setGeometry(QtCore.QRect(910, 40, 100, 140))
        self.groupBoxVertical.setMinimumSize(QtCore.QSize(100, 130))
        self.groupBoxVertical.setMaximumSize(QtCore.QSize(101, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxVertical.setFont(font)
        self.groupBoxVertical.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBoxVertical.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxVertical.setObjectName("groupBoxVertical")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxVertical)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.label_2 = QtWidgets.QLabel(self.groupBoxVertical)
        self.label_2.setMinimumSize(QtCore.QSize(77, 11))
        self.label_2.setMaximumSize(QtCore.QSize(77, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)

        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(10, 490, 771, 20))
        self.horizontalScrollBar.setMinimumSize(QtCore.QSize(771, 20))
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(771, 20))
        self.horizontalScrollBar.setStyleSheet("")
        self.horizontalScrollBar.setMinimum(0)
        self.horizontalScrollBar.setMaximum(1)
        self.horizontalScrollBar.setPageStep(10000)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")

        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(780, 10, 20, 481))
        self.verticalScrollBar.setMinimumSize(QtCore.QSize(20, 481))
        self.verticalScrollBar.setMaximumSize(QtCore.QSize(20, 481))
        self.verticalScrollBar.setMinimum(-3000)
        self.verticalScrollBar.setMaximum(3000)
        self.verticalScrollBar.setPageStep(10000)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(810, 190, 201, 311))
        self.toolBox.setMinimumSize(QtCore.QSize(201, 311))
        self.toolBox.setMaximumSize(QtCore.QSize(201, 311))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.toolBox.setObjectName("toolBox")

        self.pageFactor = QtWidgets.QWidget()
        self.pageFactor.setGeometry(QtCore.QRect(0, 0, 201, 227))
        self.pageFactor.setObjectName("pageFactor")

        self.pushButtonX001 = QtWidgets.QPushButton(self.pageFactor)
        self.pushButtonX001.setGeometry(QtCore.QRect(20, 8, 40, 25))
        self.pushButtonX001.setMinimumSize(QtCore.QSize(37, 21))
        self.pushButtonX001.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonX001.setFont(font)
        self.pushButtonX001.setStyleSheet("color: rgb(0, 170, 0);")
        self.pushButtonX001.setObjectName("pushButtonX001")

        self.pushButtonX100 = QtWidgets.QPushButton(self.pageFactor)
        self.pushButtonX100.setGeometry(QtCore.QRect(20, 70, 40, 25))
        self.pushButtonX100.setMinimumSize(QtCore.QSize(37, 21))
        self.pushButtonX100.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonX100.setFont(font)
        self.pushButtonX100.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonX100.setObjectName("pushButtonX100")

        self.pushButtonX010 = QtWidgets.QPushButton(self.pageFactor)
        self.pushButtonX010.setGeometry(QtCore.QRect(20, 40, 40, 25))
        self.pushButtonX010.setMinimumSize(QtCore.QSize(37, 21))
        self.pushButtonX010.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonX010.setFont(font)
        self.pushButtonX010.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonX010.setObjectName("pushButtonX010")

        self.label_9 = QtWidgets.QLabel(self.pageFactor)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_11 = QtWidgets.QLabel(self.pageFactor)
        self.label_11.setGeometry(QtCore.QRect(80, 40, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.pageFactor)
        self.label_12.setGeometry(QtCore.QRect(80, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.toolBox.addItem(self.pageFactor, "")

        self.pageStatistics = QtWidgets.QWidget()
        self.pageStatistics.setGeometry(QtCore.QRect(0, 0, 201, 227))
        self.pageStatistics.setObjectName("pageStatistics")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pageStatistics)
        self.gridLayout_6.setObjectName("gridLayout_6")

        self.label = QtWidgets.QLabel(self.pageStatistics)
        self.label.setMinimumSize(QtCore.QSize(80, 25))
        self.label.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)

        self.labelMinV = QtWidgets.QLabel(self.pageStatistics)
        self.labelMinV.setMinimumSize(QtCore.QSize(80, 25))
        self.labelMinV.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelMinV.setFont(font)
        self.labelMinV.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelMinV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMinV.setObjectName("labelMinV")
        self.gridLayout_6.addWidget(self.labelMinV, 1, 1, 1, 1)

        self.labelAvgV = QtWidgets.QLabel(self.pageStatistics)
        self.labelAvgV.setMinimumSize(QtCore.QSize(80, 25))
        self.labelAvgV.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelAvgV.setFont(font)
        self.labelAvgV.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelAvgV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAvgV.setObjectName("labelAvgV")
        self.gridLayout_6.addWidget(self.labelAvgV, 2, 1, 1, 1)

        self.label_6 = QtWidgets.QLabel(self.pageStatistics)
        self.label_6.setMinimumSize(QtCore.QSize(80, 25))
        self.label_6.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 4, 0, 1, 1)

        self.label_5 = QtWidgets.QLabel(self.pageStatistics)
        self.label_5.setMinimumSize(QtCore.QSize(80, 25))
        self.label_5.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)

        self.label_7 = QtWidgets.QLabel(self.pageStatistics)
        self.label_7.setMinimumSize(QtCore.QSize(80, 25))
        self.label_7.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 3, 0, 1, 1)

        self.label_10 = QtWidgets.QLabel(self.pageStatistics)
        self.label_10.setMinimumSize(QtCore.QSize(80, 25))
        self.label_10.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)

        self.labelPPV = QtWidgets.QLabel(self.pageStatistics)
        self.labelPPV.setMinimumSize(QtCore.QSize(80, 25))
        self.labelPPV.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelPPV.setFont(font)
        self.labelPPV.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPPV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPPV.setObjectName("labelPPV")
        self.gridLayout_6.addWidget(self.labelPPV, 3, 1, 1, 1)

        self.labelMaxV = QtWidgets.QLabel(self.pageStatistics)
        self.labelMaxV.setMinimumSize(QtCore.QSize(80, 25))
        self.labelMaxV.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelMaxV.setFont(font)
        self.labelMaxV.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelMaxV.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMaxV.setObjectName("labelMaxV")
        self.gridLayout_6.addWidget(self.labelMaxV, 0, 1, 1, 1)

        self.labelFrequency = QtWidgets.QLabel(self.pageStatistics)
        self.labelFrequency.setMinimumSize(QtCore.QSize(80, 25))
        self.labelFrequency.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelFrequency.setFont(font)
        self.labelFrequency.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelFrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFrequency.setObjectName("labelFrequency")
        self.gridLayout_6.addWidget(self.labelFrequency, 4, 1, 1, 1)

        self.label_13 = QtWidgets.QLabel(self.pageStatistics)
        self.label_13.setMinimumSize(QtCore.QSize(80, 25))
        self.label_13.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 5, 0, 1, 1)

        self.labelPeriod = QtWidgets.QLabel(self.pageStatistics)
        self.labelPeriod.setMinimumSize(QtCore.QSize(80, 25))
        self.labelPeriod.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelPeriod.setFont(font)
        self.labelPeriod.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelPeriod.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPeriod.setObjectName("labelPeriod")
        self.gridLayout_6.addWidget(self.labelPeriod, 5, 1, 1, 1)

        self.toolBox.addItem(self.pageStatistics, "")

        self.pageCursors = QtWidgets.QWidget()
        self.pageCursors.setObjectName("pageCursors")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageCursors)
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.label_8 = QtWidgets.QLabel(self.pageCursors)
        self.label_8.setMinimumSize(QtCore.QSize(85, 25))
        self.label_8.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 7, 0, 1, 1)

        self.labelCX1V = QtWidgets.QLabel(self.pageCursors)
        self.labelCX1V.setMinimumSize(QtCore.QSize(85, 25))
        self.labelCX1V.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCX1V.setFont(font)
        self.labelCX1V.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCX1V.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCX1V.setObjectName("labelCX1V")
        self.gridLayout_7.addWidget(self.labelCX1V, 2, 0, 1, 1)

        self.pushButtonCX2 = QtWidgets.QPushButton(self.pageCursors)
        self.pushButtonCX2.setMinimumSize(QtCore.QSize(85, 20))
        self.pushButtonCX2.setMaximumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonCX2.setFont(font)
        self.pushButtonCX2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonCX2.setObjectName("pushButtonCX2")
        self.gridLayout_7.addWidget(self.pushButtonCX2, 1, 1, 1, 1)

        self.label_3 = QtWidgets.QLabel(self.pageCursors)
        self.label_3.setMinimumSize(QtCore.QSize(85, 25))
        self.label_3.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 3, 0, 1, 1)

        self.labelCX2V = QtWidgets.QLabel(self.pageCursors)
        self.labelCX2V.setMinimumSize(QtCore.QSize(85, 25))
        self.labelCX2V.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCX2V.setFont(font)
        self.labelCX2V.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCX2V.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCX2V.setObjectName("labelCX2V")
        self.gridLayout_7.addWidget(self.labelCX2V, 2, 1, 1, 1)

        self.labelDeltaY = QtWidgets.QLabel(self.pageCursors)
        self.labelDeltaY.setMinimumSize(QtCore.QSize(85, 25))
        self.labelDeltaY.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelDeltaY.setFont(font)
        self.labelDeltaY.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelDeltaY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDeltaY.setObjectName("labelDeltaY")
        self.gridLayout_7.addWidget(self.labelDeltaY, 7, 1, 1, 1)

        self.labelDeltaX = QtWidgets.QLabel(self.pageCursors)
        self.labelDeltaX.setMinimumSize(QtCore.QSize(85, 25))
        self.labelDeltaX.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelDeltaX.setFont(font)
        self.labelDeltaX.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelDeltaX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDeltaX.setObjectName("labelDeltaX")
        self.gridLayout_7.addWidget(self.labelDeltaX, 3, 1, 1, 1)

        self.pushButtonCY2 = QtWidgets.QPushButton(self.pageCursors)
        self.pushButtonCY2.setMinimumSize(QtCore.QSize(85, 20))
        self.pushButtonCY2.setMaximumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonCY2.setFont(font)
        self.pushButtonCY2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonCY2.setObjectName("pushButton_4")
        self.gridLayout_7.addWidget(self.pushButtonCY2, 4, 1, 1, 1)

        self.pushButtonCursorsOnOff = QtWidgets.QPushButton(self.pageCursors)
        self.pushButtonCursorsOnOff.setMinimumSize(QtCore.QSize(177, 20))
        self.pushButtonCursorsOnOff.setMaximumSize(QtCore.QSize(178, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonCursorsOnOff.setFont(font)
        self.pushButtonCursorsOnOff.setObjectName("pushButtonCursorsOnOff")
        self.gridLayout_7.addWidget(self.pushButtonCursorsOnOff, 0, 0, 1, 2)

        self.pushButtonCX1 = QtWidgets.QPushButton(self.pageCursors)
        self.pushButtonCX1.setMinimumSize(QtCore.QSize(85, 20))
        self.pushButtonCX1.setMaximumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonCX1.setFont(font)
        self.pushButtonCX1.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonCX1.setObjectName("pushButtonCX1")
        self.gridLayout_7.addWidget(self.pushButtonCX1, 1, 0, 1, 1)

        self.pushButtonCY1 = QtWidgets.QPushButton(self.pageCursors)
        self.pushButtonCY1.setMinimumSize(QtCore.QSize(85, 20))
        self.pushButtonCY1.setMaximumSize(QtCore.QSize(85, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButtonCY1.setFont(font)
        self.pushButtonCY1.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButtonCY1.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButtonCY1, 4, 0, 1, 1)

        self.labelCY1V = QtWidgets.QLabel(self.pageCursors)
        self.labelCY1V.setMinimumSize(QtCore.QSize(85, 25))
        self.labelCY1V.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCY1V.setFont(font)
        self.labelCY1V.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCY1V.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCY1V.setObjectName("labelCY1V")
        self.gridLayout_7.addWidget(self.labelCY1V, 5, 0, 1, 1)

        self.labelCY2V = QtWidgets.QLabel(self.pageCursors)
        self.labelCY2V.setMinimumSize(QtCore.QSize(85, 25))
        self.labelCY2V.setMaximumSize(QtCore.QSize(85, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labelCY2V.setFont(font)
        self.labelCY2V.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelCY2V.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCY2V.setObjectName("labelCY2V")
        self.gridLayout_7.addWidget(self.labelCY2V, 5, 1, 1, 1)

        self.toolBox.addItem(self.pageCursors, "")

        self.dialVVO = QtWidgets.QDial(self.groupBoxVertical)
        self.dialVVO.setEnabled(True)
        self.dialVVO.setMinimumSize(QtCore.QSize(77, 74))
        self.dialVVO.setMaximumSize(QtCore.QSize(77, 77))
        self.dialVVO.setMinimum(1)
        self.dialVVO.setMaximum(16)
        self.dialVVO.setObjectName("dialVVO")
        self.gridLayout_2.addWidget(self.dialVVO, 0, 0, 1, 1)

        self.groupBoxHorizontal = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxHorizontal.setGeometry(QtCore.QRect(807, 40, 100, 140))
        self.groupBoxHorizontal.setMinimumSize(QtCore.QSize(100, 131))
        self.groupBoxHorizontal.setMaximumSize(QtCore.QSize(101, 150))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxHorizontal.setFont(font)
        self.groupBoxHorizontal.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBoxHorizontal.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxHorizontal.setObjectName("groupBoxHorizontal")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxHorizontal)
        self.gridLayout.setObjectName("gridLayout")

        self.dialHTB = QtWidgets.QDial(self.groupBoxHorizontal)
        self.dialHTB.setMinimumSize(QtCore.QSize(77, 74))
        self.dialHTB.setMaximumSize(QtCore.QSize(77, 77))
        self.dialHTB.setMinimum(1)
        self.dialHTB.setMaximum(14)
        self.dialHTB.setObjectName("dialHTB")
        self.gridLayout.addWidget(self.dialHTB, 0, 0, 1, 1)

        self.label_4 = QtWidgets.QLabel(self.groupBoxHorizontal)
        self.label_4.setMinimumSize(QtCore.QSize(77, 11))
        self.label_4.setMaximumSize(QtCore.QSize(77, 11))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonStartStop.setText(_translate("MainWindow", "START STOP"))
        self.pushButtonClear.setText(_translate("MainWindow", "CLEAR DATA"))
        self.groupBoxHorizontal.setTitle(_translate("MainWindow", "HORIZONTAL"))
        self.label_4.setText(_translate("MainWindow", "SEC/DIV"))
        self.groupBoxVertical.setTitle(_translate("MainWindow", "VERTICAL"))
        self.label_2.setText(_translate("MainWindow", "VOLTS/DIV"))
        self.pushButtonX001.setText(_translate("MainWindow", "x1"))
        self.pushButtonX100.setText(_translate("MainWindow", "x100"))
        self.pushButtonX010.setText(_translate("MainWindow", "x10"))
        self.label_9.setText(_translate("MainWindow", "Range: (0 ; 3.3V)"))
        self.label_11.setText(_translate("MainWindow", "Range: (0 ; 33V)"))
        self.label_12.setText(_translate("MainWindow", "Range: (0 ; 330V)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageFactor), _translate("MainWindow", "FACTOR"))
        self.label.setText(_translate("MainWindow", "Max value [mV]:"))
        self.labelMinV.setText(_translate("MainWindow", "0"))
        self.labelAvgV.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Frequency [Hz]:"))
        self.label_5.setText(_translate("MainWindow", "Min value [mV]:"))
        self.label_7.setText(_translate("MainWindow", "PP value [mV]:"))
        self.label_10.setText(_translate("MainWindow", "Avg value [mV]:"))
        self.labelPPV.setText(_translate("MainWindow", "0"))
        self.labelMaxV.setText(_translate("MainWindow", "0"))
        self.labelFrequency.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Period [ms]:"))
        self.labelPeriod.setText(_translate("MainWindow", "0"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageStatistics), _translate("MainWindow", "STATISTICS"))
        self.label_8.setText(_translate("MainWindow", "Delta(Y1,Y2):"))
        self.labelCX1V.setText(_translate("MainWindow", "0"))
        self.pushButtonCX2.setText(_translate("MainWindow", "X2"))
        self.label_3.setText(_translate("MainWindow", "Delta(X1,X2):"))
        self.labelCX2V.setText(_translate("MainWindow", "0"))
        self.labelDeltaY.setText(_translate("MainWindow", "0"))
        self.labelDeltaX.setText(_translate("MainWindow", "0"))
        self.pushButtonCY2.setText(_translate("MainWindow", "Y2"))
        self.pushButtonCursorsOnOff.setText(_translate("MainWindow", "ON / OFF"))
        self.pushButtonCX1.setText(_translate("MainWindow", "X1"))
        self.pushButtonCY1.setText(_translate("MainWindow", "Y1"))
        self.labelCY1V.setText(_translate("MainWindow", "0"))
        self.labelCY2V.setText(_translate("MainWindow", "0"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageCursors), _translate("MainWindow", "CURSORS"))


class Oscilloscope(pg.PlotWidget):
    def __init__(self, parent=None, plotItem=None, **kargs):
        super().__init__(parent=parent, **kargs)

        styles = {}
        self.setLabel("left", "mV", **styles)
        self.setLabel("bottom", "us", **styles)

        self.showGrid(x=True, y=True)
        self.setXRange(0, 1, padding=0.02)
        self.setYRange(-500, 3500, padding=0.02)

        self.pen_ch1 = pg.mkPen(color="y", width=1)

        self.pen_cursor = pg.mkPen(color="g", width=2)

        self.plot_ch([0, 0], [0, 0])

        # self.plot_cursor([0, 0], [0, 0])  # [0, 0], [-100000, 100000]
        self.plot_cx1([0, 0], [0, 0])
        self.plot_cx2([0, 0], [0, 0])
        self.plot_cy1([0, 0], [0, 0])
        self.plot_cy2([0, 0], [0, 0])

    def plot_ch(self, x, y, ch=1):
        # rysowanie linii
        self.data_line_ch = self.plot(x, y, pen=self.pen_ch1)

        # rysowanie punktów
        # self.data_line_ch = self.plot(x, y, pen=None, symbol='o',symbolBrush=pg.mkBrush(255,255,0,255), symbolSize=7)

    def update_ch(self, x, y, ch=1):
        self.data_line_ch.setData(x, y)

    # def plot_cursor(self, x, y, ch=2):
    # self.cursor_ch = self.plot(x, y, pen=self.pen_cursor)

    # def update_cursor(self, x, y, ch=2):
    # self.cursor_ch.setData(x, y)

    def plot_cx1(self, x, y, ch=2):
        self.cx1_ch = self.plot(x, y, pen=self.pen_cursor)

    def update_cx1(self, x, y, ch=2):
        self.cx1_ch.setData(x, y)

    def plot_cx2(self, x, y, ch=2):
        self.cx2_ch = self.plot(x, y, pen=self.pen_cursor)

    def update_cx2(self, x, y, ch=2):
        self.cx2_ch.setData(x, y)

    def plot_cy1(self, x, y, ch=2):
        self.cy1_ch = self.plot(x, y, pen=self.pen_cursor)

    def update_cy1(self, x, y, ch=2):
        self.cy1_ch.setData(x, y)

    def plot_cy2(self, x, y, ch=2):
        self.cy2_ch = self.plot(x, y, pen=self.pen_cursor)

    def update_cy2(self, x, y, ch=2):
        self.cy2_ch.setData(x, y)
